# Generated by Django 4.1.4 on 2023-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_paragraph_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок'),
        ),
    ]
