# Generated by Django 4.1.4 on 2023-01-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_paragraph_image_alter_paragraph_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Страница "Востребованность"',
            },
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Параграф', 'verbose_name_plural': 'Параграфы на Главной'},
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
