# Generated by Django 4.1.4 on 2023-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_demandpage_delete_profession_alter_paragraph_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandpage',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
