# Generated by Django 4.1.4 on 2023-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_demandpage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.IntegerField(verbose_name='Средняя З/П')),
                ('average_salary_web', models.IntegerField(verbose_name='Средняя З/П - Web-разработчик')),
                ('vacancies', models.IntegerField(verbose_name='Количество вакансий')),
                ('vacancies_web', models.IntegerField(verbose_name='Количество вакансий - Web-разработчик')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
            },
        ),
    ]
