# Generated by Django 4.1.4 on 2023-01-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_skillspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Страница "Последние вакансии"',
            },
        ),
    ]
